"use client";
import Link from "next/link";
import { useMemo } from "react";
import { ArrowUpDown, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { EmptyState } from '@/components/common/empty-state';
import { ErrorState } from '@/components/common/error-state';
import { LoadingState } from '@/components/common/loading-state';
import type { PaginatedCustomers } from '@/types';
export function CustomerTable({ data, isLoading, isError, page, sortDirection, onPageChange, onRefresh, onToggleSort }: { data?: PaginatedCustomers; isLoading: boolean; isError: boolean; page: number; sortDirection: 'asc' | 'desc'; onPageChange: (page: number) => void; onRefresh: () => void; onToggleSort: () => void }): React.JSX.Element { const customers = useMemo(() => data?.data.slice().sort((left, right) => { const comparison = `${left.lastName} ${left.firstName}`.localeCompare(`${right.lastName} ${right.firstName}`); return sortDirection === 'asc' ? comparison : -comparison; }) ?? [], [data?.data, sortDirection]); if (isLoading) return <LoadingState />; if (isError) return <ErrorState title="Couldn’t load customers" description="Customer records are unavailable right now." onRetry={onRefresh} />; if (!customers.length || !data) return <EmptyState title="No customers found" description="Try changing your search or add a new customer." />; return <><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-y text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3"><button type="button" onClick={onToggleSort} className="inline-flex items-center gap-1 rounded-sm hover:text-slate-900 dark:hover:text-slate-100">Customer <ArrowUpDown className="size-3" /><span className="sr-only">Sort customer names {sortDirection === 'asc' ? 'descending' : 'ascending'}</span></button></th><th className="px-3 py-3">Email</th><th className="px-3 py-3">Phone</th><th className="px-3 py-3">Added</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.id} className="border-b last:border-0 transition-colors hover:bg-slate-50 dark:hover:bg-slate-800"><td className="px-3 py-4 font-medium"><Link className="rounded-sm hover:text-blue-600" href={`/customers/${customer.id}`}>{customer.firstName} {customer.lastName}</Link></td><td className="px-3 py-4 text-slate-500">{customer.email ?? '—'}</td><td className="px-3 py-4 text-slate-500">{customer.phone}</td><td className="px-3 py-4 text-slate-500">{new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(customer.createdAt))}</td></tr>)}</tbody></table></div><div className="mt-4 flex flex-col gap-3 text-sm sm:flex-row sm:items-center sm:justify-between"><span className="text-slate-500">{data.total} customers</span><div className="flex gap-2"><Button variant="outline" size="sm" onClick={onRefresh}><RefreshCw className="size-3" />Refresh</Button><Button variant="outline" size="sm" disabled={page === 1} onClick={() => onPageChange(page - 1)}>Previous</Button><Button variant="outline" size="sm" disabled={page >= data.totalPages} onClick={() => onPageChange(page + 1)}>Next</Button></div></div></>; }
